version: '3.6'

services:

   #Defining Apache tomcat
   tomcat-main:
      image: tomcat:8-jdk8
      container_name: container-tomcat
      ports:
         - 8080:8080
      volumes:
         [
            "../docker-storage/tomcat-storage/conf/Catalina/localhost:/usr/local/tomcat/conf/Catalina/localhost",
            "../docker-storage/tomcat-storage/conf/catalina.properties:/usr/local/tomcat/conf/catalina.properties",
            "../docker-storage/tomcat-storage/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml",
            "../docker-storage/tomcat-storage/apps-repo:/usr/local/tomcat/apps-repo",
            "../docker-storage/tomcat-storage/webapps:/usr/local/tomcat/webapps",
            "../docker-storage/tomcat-storage/lib-local:/usr/local/tomcat/lib-local",
            "../docker-storage/tomcat-storage/etc:/usr/local/tomcat/etc",
            "../docker-storage/tomcat-storage/logs:/usr/local/tomcat/logs",
            "../docker-storage/tomcat-storage/storage:/usr/local/tomcat/storage",
            "../docker-data:/usr/local/tomcat/data"
         ]
      environment:
         CATALINA_OPTS: "-server \
              -Xms256m -Xmx1024m -XX:PermSize=256m \
              -XX:+UseG1GC \
              -XX:InitiatingHeapOccupancyPercent=70 \
              -Djava.security.auth.login.config=/usr/local/tomcat/etc/jaas.config"
      depends_on:
         - mysql
      restart: always
      
      
   # Defining MySQL Service
   mysql:
      image: mysql:${MYSQL_VERSION}
      container_name: container-mysql
      command: --lower_case_table_names=0
      security_opt:
         - seccomp:unconfined
      volumes:
         [
            "../docker-storage/mysql-storage:/var/lib/mysql"
         ]
      environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
         - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
         - MYSQL_USER=${MYSQL_USER}
         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
         - MYSQL_DATABASE=${MYSQL_DATABASE}
      restart: always
      
   # Defining Nginx Service
   nginx:
      image: nginx:${NGINX_VERSION:-latest}
      container_name: container-nginx
      ports:
         - 80:80
      volumes:
         [
            "../docker-storage/nginx-storage/conf:/etc/nginx/conf.d",
            "../docker-storage/nginx-storage/logs:/var/log/nginx",
            "../docker-storage/nginx-storage/html:/var/www/html"
         ]
      restart: always