version: "3"

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.0.0/24
    external: false

services:
    # Defining DB Server
    mysql-db:
        image: mysql:8
        container_name: container-mysql
        restart: always
        command: --lower_case_table_names=0
        security_opt:
            - seccomp:unconfined
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: rootPassword
            TZ: Europe/Paris
        volumes:
            [
                "/home/ec2-user/aws-docker/docker-storage/mysql-storage:/var/lib/mysql",
            ]
        ports:
            - 3306:3306
        networks:
            default:
               ipv4_address: 192.168.0.2

    # Defining Nginx
    nginx: 
        image: nginx:latest
        container_name: container-nginx
        restart: always
        volumes:
            [
                "/home/ec2-user/aws-docker/docker-storage/nginx-storage/conf:/etc/nginx/conf.d",
                "/home/ec2-user/aws-docker/docker-storage/nginx-storage/logs:/var/log/nginx",
                "/home/ec2-user/aws-docker/docker-storage/nginx-storage/html:/var/www/default"
            ]
        ports:
            - 80:80
        networks:
            default:
               ipv4_address: 192.168.0.3
               
    # Defining Tomcat Web Server
    tomcat-main:
        image: tomcat:8-jdk8
        container_name: container-tomcat
        restart: always
        ports:
            - 8080:8080
        environment:
            CATALINA_OPTS: "-server \
              -Xms256m -Xmx1024m -XX:PermSize=256m \
              -XX:+UseG1GC \
              -XX:InitiatingHeapOccupancyPercent=70 \
              -Djava.security.auth.login.config=/usr/local/tomcat/etc/jaas.config"
        volumes:
            [
                "/home/ec2-user/aws-docker/docker-storage/tomcat-storage/conf/Catalina/localhost:/usr/local/tomcat/conf/Catalina/localhost",
                "/home/ec2-user/aws-docker/docker-storage/tomcat-storage/conf/catalina.properties:/usr/local/tomcat/conf/catalina.properties",
                "/home/ec2-user/aws-docker/docker-storage/tomcat-storage/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml",
                "/home/ec2-user/aws-docker/docker-storage/tomcat-storage/apps-repo:/usr/local/tomcat/apps-repo",
                "/home/ec2-user/aws-docker/docker-storage/tomcat-storage/webapps:/usr/local/tomcat/webapps",
                "/home/ec2-user/aws-docker/docker-storage/tomcat-storage/lib-local:/usr/local/tomcat/lib-local",
                "/home/ec2-user/aws-docker/docker-storage/tomcat-storage/etc:/usr/local/tomcat/etc",
                "/home/ec2-user/aws-docker/docker-storage/tomcat-storage/logs:/usr/local/tomcat/logs",
                "/home/ec2-user/aws-docker/docker-storage/tomcat-storage/storage:/usr/local/tomcat/storage",
                "/home/ec2-user/aws-docker/docker-data:/usr/local/tomcat/data",
            ]
        networks:
            default:
               ipv4_address: 192.168.0.4

       # Defining Wordpress Server
       wordpress:
          image: wordpress
          container_name: container-wordpress
          restart: always
          ports:
            - 8081:80
          environment:
            WORDPRESS_DB_HOST: 192.168.0.2
            WORDPRESS_DB_USER: wordpressRootUser
            WORDPRESS_DB_PASSWORD: wordpressRootPassword
            WORDPRESS_DB_NAME: wordPressDB
          volumes:
              [
                "/home/ec2-user/aws-docker/docker-storage/nginx-storage/html/wordpress:/var/www/html"
              ]
          depends_on:
             - mysql-db
          networks:
            default:
               ipv4_address: 192.168.0.5